#!/usr/bin/env bash
# scripts/update-perf-tracker-chart.sh — refresh the timeline charts inside
# the body of GitHub issue #1 (the perf tracker) from its accumulated comments.
#
# Two formats coexist in the comment stream:
#
#   Old (pre-2026-05-13, mobile-implicit because CI silently ran mobile):
#     ✅ 2026-05-13 06:24 UTC — perf=**53** a11y=84 bp=100 seo=100 — [run](...)
#
#   New (2026-05-13+):
#     ✅ 2026-05-13 12:52 UTC — mobile: perf=**50** a11y=84 bp=100 seo=100 · desktop: perf=**85** a11y=92 bp=100 seo=100 — [run](...)
#
# This script pulls all comments, classifies each as mobile/desktop/both,
# and emits TWO Mermaid xychart-beta charts (one per form factor) plus
# value-anchored legends. Idempotent — the markers below let us rerun
# without duplicating chart blocks.
#
# Manual:   bash scripts/update-perf-tracker-chart.sh
# Wired into perf-prod.yml: aggregator job refreshes after every cron run.
#
# Requires: gh authenticated to leni-kirilov/darivreme-monorepo, node.

set -euo pipefail

REPO="${REPO:-leni-kirilov/darivreme-monorepo}"
ISSUE_NUMBER="${ISSUE_NUMBER:-1}"

CHART_MARKER_BEGIN="<!-- perf-chart:begin (regenerated by scripts/update-perf-tracker-chart.sh) -->"
CHART_MARKER_END="<!-- perf-chart:end -->"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

gh issue view "$ISSUE_NUMBER" -R "$REPO" --json body,comments > "$TMP/issue.json"

# Per-metric drill-down (Tier 2 of the 2026-05-21 measurement upgrade) reads
# the rolled-up timeline.json from the public gh-pages bucket. Fails open if
# the file doesn't exist yet (first run after upgrade).
TIMELINE_URL="${PERF_TIMELINE_URL:-https://leni-kirilov.github.io/darivreme-perf/history/timeline.json}"
if curl -fsSL -o "$TMP/timeline.json" "$TIMELINE_URL" 2>/dev/null; then
    echo "[update] fetched timeline.json ($(wc -c < "$TMP/timeline.json") bytes)"
    HAS_TIMELINE=1
else
    echo "[update] timeline.json not available at $TIMELINE_URL — skipping per-metric drill-down"
    HAS_TIMELINE=0
fi

# Build the combined chart block via Node — parses both legacy and new
# comment formats and emits two charts with legends.
node - "$TMP/issue.json" > "$TMP/chart.md" <<'NODE'
const fs = require('fs');
const { body, comments } = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));

// Legacy (mobile-implicit) regex.
const rxLegacy = /(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})\s+UTC\s+—\s+perf=\*?\*?(\d+).*?a11y=(\d+).*?bp=(\d+).*?seo=(\d+)\s*—\s*\[run\]/;

// New format regex — captures mobile + desktop blocks. Either may be
// "(no report)" if Lighthouse crashed for that factor.
const rxNew = /(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})\s+UTC\s+—\s+mobile:\s*(?:perf=\*?\*?(\d+).*?a11y=(\d+).*?bp=(\d+).*?seo=(\d+)|\(no report\))\s*·\s*desktop:\s*(?:perf=\*?\*?(\d+).*?a11y=(\d+).*?bp=(\d+).*?seo=(\d+)|\(no report\))/;

const mobile  = [];
const desktop = [];
let droppedCaptcha = 0;

// Captcha-corrupted readings have a11y/bp/seo == 0 because Lighthouse
// audited SG-Security's challenge page instead of darivreme.com. Real
// scores are never exactly 0 (the page always has SOME a11y/seo signal).
// Skip these rows so the chart isn't dominated by spikes from a wrong URL.
// Root cause + workflow-side fix: see memory `sg-security-captcha-vs-gha`
// and the captcha detection in perf-prod.yml's aggregator job.
function isValid(r) {
    if (r.a11y === 0 || r.bp === 0 || r.seo === 0) return false;
    return true;
}

const sorted = comments
    .map(c => ({ when: new Date(c.createdAt), body: c.body }))
    .sort((a, b) => a.when - b.when);

for (const c of sorted) {
    const mNew = c.body.match(rxNew);
    if (mNew) {
        const label = `${mNew[1].slice(5)} ${mNew[2]}`;
        if (mNew[3] !== undefined) {
            const row = { label, perf:+mNew[3], a11y:+mNew[4], bp:+mNew[5], seo:+mNew[6] };
            if (isValid(row)) mobile.push(row); else droppedCaptcha++;
        }
        if (mNew[7] !== undefined) {
            const row = { label, perf:+mNew[7], a11y:+mNew[8], bp:+mNew[9], seo:+mNew[10] };
            if (isValid(row)) desktop.push(row); else droppedCaptcha++;
        }
        continue;
    }
    const mLeg = c.body.match(rxLegacy);
    if (mLeg) {
        // Legacy comments were mobile-implicit (CI bug pre-2026-05-13).
        const row = {
            label: `${mLeg[1].slice(5)} ${mLeg[2]}`,
            perf:+mLeg[3], a11y:+mLeg[4], bp:+mLeg[5], seo:+mLeg[6],
        };
        if (isValid(row)) mobile.push(row); else droppedCaptcha++;
    }
}

function summarize(arr) {
    const last = arr[arr.length - 1];
    const lo = Math.min(...arr);
    const hi = Math.max(...arr);
    return lo === hi
        ? `**${last}** (flat across all runs)`
        : `**${last}** (range ${lo}–${hi})`;
}

function buildChart(factor, rows) {
    if (rows.length === 0) {
        return `### ${factor.charAt(0).toUpperCase() + factor.slice(1)}\n\n_No data yet — first ${factor} run will populate this chart._`;
    }
    const labels = rows.map(r => `"${r.label}"`).join(', ');
    const perf   = rows.map(r => r.perf).join(', ');
    const a11y   = rows.map(r => r.a11y).join(', ');
    const bp     = rows.map(r => r.bp).join(', ');
    const seo    = rows.map(r => r.seo).join(', ');

    const perfArr = rows.map(r => r.perf);
    const a11yArr = rows.map(r => r.a11y);
    const bpArr   = rows.map(r => r.bp);
    const seoArr  = rows.map(r => r.seo);

    return `### ${factor.charAt(0).toUpperCase() + factor.slice(1)} — ${rows.length} runs

\`\`\`mermaid
---
config:
    xyChart:
        width: 900
        height: 360
---
xychart-beta
    title "Lighthouse ${factor} over time (${rows.length} runs)"
    x-axis [${labels}]
    y-axis "Score" 0 --> 100
    line "Performance"   [${perf}]
    line "Accessibility" [${a11y}]
    line "Best Practices" [${bp}]
    line "SEO"           [${seo}]
\`\`\`

**Legend** — current value per line, read off the y-axis (xychart-beta has no native legend; identify each line by value):

| Metric | Latest value |
| :-- | :-- |
| Performance    | ${summarize(perfArr)} |
| Accessibility  | ${summarize(a11yArr)} |
| Best Practices | ${summarize(bpArr)} |
| SEO            | ${summarize(seoArr)} |`;
}

if (mobile.length === 0 && desktop.length === 0) {
    console.error('No parsable comments found.');
    process.exit(2);
}

const captchaNote = droppedCaptcha > 0
    ? `\n_${droppedCaptcha} reading(s) dropped from this chart — Lighthouse audited SG-Security's captcha page instead of darivreme.com (a11y/bp/seo all returned 0). See [memory: sg-security-captcha-vs-gha] for details. Comments are preserved below for audit._`
    : '';

const out = [
    buildChart('mobile', mobile),
    '',
    '---',
    '',
    buildChart('desktop', desktop),
    '',
    '_Each datapoint is one `perf-prod.yml` run from the comments below. Pre-2026-05-13 comments are mobile-implicit (CI was silently running mobile)._' + captchaNote,
].join('\n');

process.stdout.write(out);
NODE

# Per-metric drill-down section — appended below the score charts.
if [ "$HAS_TIMELINE" = "1" ]; then
    node - "$TMP/timeline.json" >> "$TMP/chart.md" <<'NODE' || echo "[update] per-metric drill-down render failed"
const fs = require('fs');
const rows = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));

// Filter to homepage only, separate mobile vs desktop, sorted by date.
// Backfilled rows use slug "homepage" (from legacy artifact filename);
// new N=5 workflow uses slug "home". Accept both for chart continuity.
const isHome = r => r.page === 'home' || r.page === 'homepage';
const homeMobile  = rows.filter(r => isHome(r) && r.factor === 'mobile')
                        .sort((a, b) => (a.started_at || '').localeCompare(b.started_at || ''));
const homeDesktop = rows.filter(r => isHome(r) && r.factor === 'desktop')
                        .sort((a, b) => (a.started_at || '').localeCompare(b.started_at || ''));

function labelOf(r) {
    return (r.date || '').slice(5);
}

function chartFor(title, rows, key, yLabel) {
    const valid = rows.filter(r => r[key] !== null && r[key] !== undefined);
    if (valid.length === 0) return null;
    const labels = valid.map(r => `"${labelOf(r)}"`).join(', ');
    const values = valid.map(r => r[key]).join(', ');
    const min = Math.min(...valid.map(r => r[key]));
    const max = Math.max(...valid.map(r => r[key]));
    const pad = Math.max(1, (max - min) * 0.15);
    return `\`\`\`mermaid
---
config:
    xyChart:
        width: 900
        height: 220
---
xychart-beta
    title "${title}"
    x-axis [${labels}]
    y-axis "${yLabel}" ${Math.max(0, Math.floor(min - pad))} --> ${Math.ceil(max + pad)}
    line [${values}]
\`\`\``;
}

// Combine unused CSS + JS into a single "unused payload" line for shorter chart.
function withUnusedPayload(rows) {
    return rows.map(r => ({
        ...r,
        unused_payload_kb: r.unused_css_bytes != null && r.unused_js_bytes != null
            ? Math.round((r.unused_css_bytes + r.unused_js_bytes) / 1024)
            : null,
    }));
}

const m = withUnusedPayload(homeMobile);
const d = withUnusedPayload(homeDesktop);

const out = [];
out.push('');
out.push('---');
out.push('');
out.push('## Per-metric drill-down — homepage');
out.push('');
out.push('Below the rolled-up perf scores. These are the metrics the score is computed from — useful when the score wobbles and you want to know WHY. Source: `darivreme-perf:history/timeline.json` (Tier 2 of the 2026-05-21 measurement upgrade).');
out.push('');

const sections = [
    { title: 'LCP — Largest Contentful Paint (ms, lower better)',  key: 'lcp_ms',           y: 'ms' },
    { title: 'TBT — Total Blocking Time (ms, lower better)',       key: 'tbt_ms',           y: 'ms' },
    { title: 'Speed Index (ms, lower better)',                     key: 'si_ms',            y: 'ms' },
    { title: 'Unused payload — CSS + JS (KB, lower better)',       key: 'unused_payload_kb', y: 'KB' },
];

for (const s of sections) {
    const mob = chartFor(`Mobile · ${s.title}`,  m, s.key, s.y);
    const desk = chartFor(`Desktop · ${s.title}`, d, s.key, s.y);
    if (!mob && !desk) continue;
    out.push(`### ${s.title}`);
    out.push('');
    if (mob)  { out.push('**Mobile**'); out.push(''); out.push(mob);  out.push(''); }
    if (desk) { out.push('**Desktop**'); out.push(''); out.push(desk); out.push(''); }
}

out.push('_Each datapoint is the median of N=5 runs on that night (post-2026-05-21). Earlier datapoints are N=1 (legacy). See `docs/performance-status.md §Measurement upgrade` for context._');
process.stdout.write(out.join('\n') + '\n');
NODE
fi

# Splice the new chart between BEGIN/END markers. Earlier awk-based
# implementation duplicated the END marker on every run (rule-order bug)
# and didn't strip leftover chart content between accumulated markers —
# the body grew with each refresh. Node lookup is simpler + robust to
# stale markers (collapses any prior accumulation into one clean block).
node - "$TMP/issue.json" "$TMP/chart.md" "$CHART_MARKER_BEGIN" "$CHART_MARKER_END" > "$TMP/new-body.md" <<'NODE'
const fs = require('fs');
const [, , issuePath, chartPath, beginMarker, endMarker] = process.argv;
const body  = JSON.parse(fs.readFileSync(issuePath, 'utf8')).body;
const chart = fs.readFileSync(chartPath, 'utf8').trimEnd();

const beginRe = new RegExp(beginMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
const endRe   = new RegExp(endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');

const beginIdx = body.search(beginRe);
let lastEnd = -1, m;
while ((m = endRe.exec(body)) !== null) lastEnd = m.index + m[0].length;

let out;
if (beginIdx < 0) {
    console.error('[update] no existing chart block — appending');
    out = body.trimEnd() + '\n\n---\n\n## Timeline\n\n'
        + beginMarker + '\n' + chart + '\n' + endMarker + '\n';
} else {
    console.error('[update] replacing existing chart block');
    const pre  = body.slice(0, beginIdx);
    const post = (lastEnd > beginIdx) ? body.slice(lastEnd) : '';
    out = pre + beginMarker + '\n' + chart + '\n' + endMarker + post;
}
process.stdout.write(out);
NODE

gh issue edit "$ISSUE_NUMBER" -R "$REPO" --body-file "$TMP/new-body.md" > /dev/null
echo "[done] issue #${ISSUE_NUMBER} body updated with chart ($(wc -l < "$TMP/new-body.md") lines)"
